### ISSUE TITLE
prefedit.c format-overflow warning

### ISSUE THREAD

**Issue by rabidt** [LuminariMUD/Luminari-Source#4] opened 2020-04-22 01:27 UTC
prefedit.c:116:37: warning: \u2018%s\u2019 directive writing up to 3 bytes into a region of size between 1 and 10 [-Wformat-overflow=]
   sprintf(prompt_string, "%s%s%s%s%s%s%s%s",
                                     ^~

**Comment by Odoth** [comment] 2020-04-22 05:08
Duplicate of #9

**Closed** 2020-04-22 05:07 UTC
Labels: bug, duplicate
